import s from '../styles/Home.module.sass';

import type { NextPage } from 'next';
import Head from 'next/head';

import { Cards } from "../interfaces/cards";
import { Slider } from "../components/Slider/Slider";
import { Card } from "../components/Card/Card";


const Home: NextPage = () => {

    const cardsAdult: Cards[] = [
        {
            title: "Взрослый",
            src: "/assets/adult.png",
            info: [
                "Менее тяжелые формы СМА могут возникать и диагностироваться в зрелом возрасте.",
                "По сравнению с СМА у детей, СМА у взрослых может иметь более легкие симптомы, но без патогенетической терапии пациенты со СМА 2-3 типа неуклонно теряют двигательные навыки.",
                "По сравнению с СМА в детстве, течение СМА у взрослых может быть более коварным и трудным для распознавания.",
            ]
        },
    ];

    const cardsChild: Cards[] = [
        {
            title: "Ребенок",
            src: "/assets/child.png",
            info: [
                "Ребенок, плохо удерживающий голову, когда ему придают сидячее положение, с вялымидвижениями нижних конечностей или с трудом тянущийся к предметам, но при этом сосмысленным и ярким взглядом, улыбающийся и социально активный, вызывает настороженностьв отношении наличия СМА.",
                "Младенцам со СМА необходимо экстренное направление к специалисту, ранняя диагностика и обеспечение терапией, спасающей жизнь, поскольку эти мотонейроны очень быстро подвергаются дегенерации при прогрессировании заболевания",
            ]
        },
    ];

    return (
        <div className={s.container}>
            <Head>
                <title>Мир врача</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <header className={s.header}>
                <h1 className={s.title}>А вдруг СМА?</h1>
                <h2 className={s.description}>Выберите, кто Ваш пациент:</h2>
            </header>

            <main className={s.main}>
                <div className={s.main__wrapper}>
                    <div className={s.card__wrapper}>
                        {cardsAdult.map((card: Cards, key: number) => (
                            <Card title={card.title} src={card.src} info={card.info} key={key}/>
                        ))}
                        {cardsChild.map((card: Cards, key: number) => (
                            <Card title={card.title} src={card.src} info={card.info} key={key}/>
                        ))}
                    </div>
                    <Slider/>
                </div>
            </main>
        </div>
    )
};

export default Home
